### ISSUE TITLE
 Overhaul of pseudofamily identifiers and tarballs

### ISSUE THREAD

**Issue by mfherbst** [JuliaMolSim/PseudoPotentialData.jl#1]
The current identfier system is a little confusing and not fully consistent.

Moreover current artefacts don't contain the pseudofiles under a consistent name either (e.g. the HGH ones sometimes contain two pseudopotential files for one element --- one for fullcore and one for semicore).

Both needs to be harmonised here and in https://github.com/JuliaMolSim/PseudoLibrary.

**Comment by mfherbst** [comment]
@unkcpz We discussed names for pseudopotentials by mail at some point. Have you guys at SSSP / Aiida reached a conclusion on that front ?

**Comment by unkcpz** [comment]
@mfherbst, at the moment I change the schema to partially as you suggested (more detail to metadata and only distinguishable arguments in the filename). Next week I'll have a in person meeting with Nicola, and will confirm on it. I'll keep you updated.

**Comment by mfherbst** [comment]
Thanks @unkcpz . Any news ?

**Comment by unkcpz** [comment]
Had the meeting yesterday, I reply the decision on email.

The typical naming will be: `Si.nc.pbe.4E.dojo.v0_4_1.oncvpsp3.std.upf`. Where after the version, fields are optional as additional infos.

**Comment by mfherbst** [comment]
Ok, so we will use the same for families, but just dropping the element-specific aspects.
